### ISSUE TITLE
Update Docs: Shell Agnostic Method

### ISSUE THREAD

**Issue by edm00se** [kentcdodds/netlify-shortener#10]
I've discovered I can use a shell agnostic implementation in place of manually wiring up a shell script in BASH, etc. It makes use of `npm link` functionality. There's a screen shot below of what's needed. I'm working on a PR to submit that should reflect this in the readme.

Required:

- a repo (project dir) w/ `_redirects` file and a `package.json` with `baseUrl` and `shorten` script values

Add:

- to the `package.json`:
  ```json
  "bin": { "shorten": "cli.j.s" }
  ```
- to the project, add `cli.js` with the following:
  ```js
  #!/usr/bin/env node
  require('netlify-shortener');
  ```

Register:

- from your project dir, run `npm link`, which will register your project's `bin` names against their respective actions, running from your project path

![image](https://user-images.githubusercontent.com/622118/52371749-f8503380-2a1b-11e9-984e-6cd8e6e0d425.png)

Use remains the same, with `shorten <url> <name>` syntax.

**Comment by kentcdodds** [comment]
I love it! Yes, if you can add docs on how to do that, I'd appreciate it :)

**Comment by edm00se** [comment]
It'll follow the description above (minus screen shot), but I'll try to make it readable for nearly anyone.

**Comment by edm00se** [comment]
I've created the PR, #11. Let me know if we should massage the description; I tried to make it easy enough for someone with little experience to follow.

**Comment by kentcdodds** [comment]
Perfect. I like it :+1:
