### ISSUE TITLE
[Idea] do fetch before adding new links

### ISSUE THREAD

**Issue by huchenme** [kentcdodds/netlify-shortener#13]
Just now I use CLI to add a new link but failed because I forgot to `git pull` the latest changes as I did some edits over the phone.

I think I will keep forgetting again sometime later, it will be good if we could do a `git pull` first before starting to add new links, what do you think?

**Comment by huchenme** [comment]
hmm, I just checked the source code it actually does a pull before everything but in my experience, it does not do `git pull`, and I am using `1.0.4`

![screenshot 2019-03-02 at 6 03 40 pm](https://user-images.githubusercontent.com/2078389/53680375-abf3cd00-3d15-11e9-8e65-b7614acf9d86.jpg)

**Comment by kentcdodds** [comment]
If you figure out what the problem is the a pull rust would be welcome.

**Comment by kentcdodds** [comment]
I'm pretty sure this has been implemented now :)
