### ISSUE TITLE
Wrong package.json path resolve

### ISSUE THREAD

**Issue by sylvesteraswin** [kentcdodds/netlify-shortener#23]
- `netlify-shortener` 2.1.0:
- `node` version: 12.8.1
- `npm` (or `yarn`) version: 6.10.3

Relevant code or config

```javascript
```

What you did:

I install the packages as instructed in the README

What happened:

```
const {
  pkg: {
    baseUrl = 'https://update-baseUrl-in-your-package.json'
  },
  path: pkgPath
} = readPkg.sync({
  cwd: path.join(__dirname, '../..')
```

`path.join(__dirname, '../..')` in the above block always refers to `<project>/node_modules` and as a result I am always getting this error `baseUrl = 'https://update-baseUrl-in-your-package.json'`

Reproduction repository:

Problem description:

Suggested solution:

**Comment by innocenzi** [comment]
When I read the result of 
```js
readPkg.sync({
  cwd: path.join(__dirname, '../..')
})
```

I see that the key is `packageJson` instead of `pkg`. Probably has something to do with https://github.com/sindresorhus/read-pkg-up/releases/tag/v7.0.0. 

The fix that worked for me was obviously to change `pkg` to `packageJson`. I won't PR because I'm not sure what it will affect. 

@kentcdodds

**Comment by JamalBelilet** [comment]
It’s already fixed on the GitHub repo just check out the latest commit where he changed pkg to packageJson as @hawezo mentioned.

**Comment by innocenzi** [comment]
Oh, yes, my bad. So it just needs to be published to NPM.

**Comment by kentcdodds** [comment]
There was an issue with the last build and the most recent version wasn't released. I've just kicked it off again and it worked this time so this should be fixed now. Sorry about that.
