### ISSUE TITLE
Feature request: support for URLs without http/https

### ISSUE THREAD

**Issue by oisinq** [kentcdodds/netlify-shortener#29]
Hi! I really like this project.

I think it could be cool to support URLs that don't have `http://` or `https://` at the start, but would otherwise be valid. I'm used to my browser accepting URLs like that, and it saves a little bit of typing.

<img width="799" alt="Screenshot 2020-05-24 at 15 11 40" src="https://user-images.githubusercontent.com/5693967/82756240-e93bf300-9dd0-11ea-8e2b-478221461567.png">

I'm happy to give this a go myself if this seems like a relevant feature for this project. I've never contributed to an npm package before, but I'd be happy to give it a try.

**Comment by kentcdodds** [comment]
Hi @oisinq!

I think this is fine. We could default the protocol to `https` if it's not provided.

Happy to help you get your first open source pull request merged. This might be a helpful resource for you: https://makeapullrequest.com

**Comment by MichaelDeBoey** [comment]
Closed by #30
