### ISSUE TITLE
Use package.json's homepage field instead of baseUrl

### ISSUE THREAD

**Issue by zhouzi** [kentcdodds/netlify-shortener#34]
**Problem description:**

Currently, `netlify-shortener` uses its own custom `baseUrl` field in the `package.json`. I believe it'd be nice to use an existing convention and avoid creating a new one. I feel like the `package.json`'s `homepage` fits perfectly for this use case.

(For example, it's what `create-react-app` uses for [generating the app's URL](https://create-react-app.dev/docs/deployment/#building-for-relative-paths))

**Suggested solution:**

1. Add a deprecation message when the user has a `baseUrl`, encouraging to use `homepage` instead.
2. Add support for both `homepage` and `baseUrl`, the latter having the priority since it has been the documented way so far.
3. Release a minor version.
4. Remove the deprecation message and support for `baseUrl`.
5. Release a major version.

What do you think? 😄 I'm happy to submit a PR if it sounds good.

**Comment by kentcdodds** [comment]
I'd rather just support both and not document the `baseUrl`. This is such a simple project that it would be a shame to require people to give it any attention if they don't want to.

**Comment by zhouzi** [comment]
Totally agree 👍 I just submitted #35
