### ISSUE TITLE
Subdomains?

### ISSUE THREAD

**Issue by ryantheleach** [kentcdodds/netlify-shortener#40]
Is it possible to use this with subdomains?

**Comment by kentcdodds** [comment]
Do you mean:

```
https://sub.domain.com/short-url1
https://sub.domain.com/short-url2
https://sub.domain.com/short-url3
```

If so, then yes! You need to [configure netlify for your subdomain](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/).

If you mean:

```
https://short-url1.domain.com
https://short-url2.domain.com
https://short-url3.domain.com
```

Then I'm afraid not. You'll have to configure DNS records for each one of those.

I hope that helps! Good luck!
