### ISSUE TITLE
Feature request: Multi-domain redirects

### ISSUE THREAD

**Issue by adamdjbrett** [kentcdodds/netlify-shortener#47]
Would it be possible to keep this simple and add the ability for it to handle multiple domains?

**Comment by kentcdodds** [comment]
Do you have specific suggestions of how to do that?

**Comment by adamdjbrett** [comment]
Sadly I do not.

**Comment by adamdjbrett** [comment]
> Do you have specific suggestions of how to do that?

I figured it out. In netlify I added the secondary domains to the repo so the old link domain is migrated over to the new one.
