### ISSUE TITLE
Feature request: Use alternate commit messages

### ISSUE THREAD

**Issue by trillium** [kentcdodds/netlify-shortener#48]
## Overview

I prefer to use semantic commit messages, is there a way I can do somwething like `style: Format links` instead of `format links` ?

Can this be a config option in the `package.json` somehow?

## Info
- `netlify-shortener` version: `1.0.4`
- `node` version: `v21.6.2`
- `npm` version: `10.2.4`

Relevant code or config

```javascript
function commitAndPush(short, longLink, cwd) {
  const message = longLink ? `${short} -> ${longLink}` : 'format links';
  console.log(`committing: ${message}`);
  spawnSync('git', ['commit', '-am', message], {
    stdio: 'inherit',
    cwd
  });
  console.log('pushing');
  spawnSync('git', ['push'], {
    stdio: 'inherit',
    cwd
  });
}
```

**Comment by kentcdodds** [comment]
Hello @trillium!

Thanks for your interest. I don't think adding complexity to this package (even a little bit of it) is necessary. Feel free to fork if the commit message is important to you.
