### ISSUE TITLE
[Discussion] GUI for netlify-shortener with git-gateway

### ISSUE THREAD

**Issue by swyxio** [kentcdodds/netlify-shortener#9]
not a bug, not a feature request, just an idea.

the way [NetlifyCMS](https://www.netlifycms.org/) works is it is a drop-in UI on top of your existing site to help you manage your markdown based content, including creating and merging pull requests for content, all within a GUI. It does this using the [Git Gateway](https://www.netlify.com/docs/git-gateway/). So you never touch your terminal or editor and have a wordpress like experience on your completely static/serverless/git based site.

this strikes me as not too different from the flow needed to edit and manage url shorteners. we just need a GUI that understands `_redirects` and can link to Git Gateway.

copying @erquhart and @bcomnes who may know more about feasibility. and of course anyone who wants to take this up is super welcome

**Comment by bcomnes** [comment]
Seems feasible!

**Comment by erquhart** [comment]
It's definitely feasible, agreed.

@sw-yx do you think this kind of UI would be useful for a shortener, though? URL shortening is the kind of thing you want to do in about 1.5 seconds, so the binary approach makes a lot of sense. I suppose if you're managing long living urls, rather than throw-away social links, maybe it'd be a good fit for that.

**Comment by kentcdodds** [comment]
> URL shortening is the kind of thing you want to do in about 1.5 seconds

Cannot agree more. And if I'm on my phone or something I have https://kcd.im/shorten which I can use to have a GUI to quickly add a new link 🤷‍♂️

**Comment by swyxio** [comment]
hrm. i never thought about shortening the shortener. well played!

**Comment by davidhund** [comment]
(Apologies if it's bad form to comment on a closed issue. I thought it better than to open a new, similar, one…)

I can totally see the reasoning for staying CLI-only. 
However: I would love to implement this for my team of which some people are not comfortable with either the CLI or Git (or even have access to the repo).

Having _some_ GUI to manage the redirects would be great for them. 

Although 'feasible', at the moment the `_redirects` are not editable in Netlify CMS, right?
